version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pyqt:
        patterns: ["PyQt6*"]
      yt-dlp:
        patterns: ["yt-dlp"]
      other:
        patterns: ["*"]
        exclude-patterns: ["PyQt6*", "yt-dlp"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      major-actions:
        patterns: ["*"]
        update-types: ["major"]
      minor-patch-actions:
        patterns: ["*"]
        update-types: ["minor", "patch"]
